spring:
  datasource:
    url: jdbc:mysql://chw-dev-database-1.ct21ygalzs5e.us-east-2.rds.amazonaws.com:3306/user_service
    username: admin
    password: ChwPassword
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false
      
  mail:
    host: email-smtp.us-east-2.amazonaws.com
    port: 587
    username: AKIAQYQFGXKB235VZYKO
    password: BLh918oBepjlHtI+PtbdB7BW6e+XZVN/jE8uMJ3QmWM2
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
        transport:
          protocol: smtp
        debug: true
