server:
  port: 8080
  servlet:
    context-path: /user-service
  tomcat:
    accept-count: 1000
    max-connections: 10000
    max-threads: 300
    min-spare-threads: 200
    max-swallow-size: 4MB
    max-http-post-size: 2MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
  mail:
    host: email-smtp.us-east-2.amazonaws.com
    port: 587
    username: AKIAQYQFGXKB235VZYKO
    password: BLh918oBepjlHtI+PtbdB7BW6e+XZVN/jE8uMJ3QmWM2
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
        transport:
          protocol: smtp
        debug: false

management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springboot.web: ERROR
    com.chw: INFO
    org.springframework: DEBUG
    com.zaxxer: DEBUG
    root: ERROR
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}-%L - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}-%L - %msg%n'
  file: ${java.io.tmpdir}/admin-service.log
