server:
  port: 8080
  servlet:
    context-path: /user-authentication-service
  tomcat:
    accept-count: 1000
    max-connections: 10000
    max-threads: 300
    min-spare-threads: 200
    max-swallow-size: 4MB
    max-http-post-size: 2MB

spring:
  datasource:
    url: jdbc:mysql://chw-dev-database-1.ct21ygalzs5e.us-east-2.rds.amazonaws.com:3306/user_service
    username: admin
    password: ChwPassword
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    database: mysql
    hibernate:
      use-new-id-generator-mappings: false

management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springboot.web: ERROR
    com.chw: INFO
    org.springframework: DEBUG
    com.zaxxer: DEBUG
    root: ERROR
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}-%L - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}-%L - %msg%n'
  file: ${java.io.tmpdir}/admin-service.log